#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2024
#

services:
  order-service:
    ports:
      - "5005:5005"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.jar

  inventory-service:
    ports:
      - "5006:5006"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -jar /app.jar

  delivery-service:
    ports:
      - "5007:5007"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -jar /app.jar
