#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2024
#

services:
  order-service:
    ports:
      - "5005:5005"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.jar

  inventory-service:
    ports:
      - "5006:5005"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.jar

  delivery-service:
    ports:
      - "5007:5005"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.jar

  discovery-server:
    ports:
      - "5008:5005"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.jar

  api-gateway:
      ports:
        - "5009:5005"
      command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app.jar
